DATE_FORMAT = '%Y-%m-%d %H:%M:%S'
bark_token = ''
teams_webhook = ''
teams_user_mentions = []
dingtalk_webhook = ''
dingtalk_user_mentions = []
telegram_token = ''
telegram_chat_id = ''
wechat_webhook = ''
wechat_user_mentions = []
wechat_user_mentions_mobile = []
